server {
    listen 80;
    server_name whirl.uz www.whirl.uz;
    root /var/www/whirl;
    index index.html;

    location / {
        try_files $uri $uri/ /whirl.html;
    }

    location /gzs/ {
        proxy_pass http://10.0.1.25/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /smartparking/ {
        proxy_pass http://10.0.1.206/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/ {
        proxy_pass http://10.0.1.25:5036;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /swagger/ {
        proxy_pass http://10.0.1.25:5036;
        proxy_set_header Host $host;
    }

    location /Billing/ {
        proxy_pass http://10.0.1.206:5121;
        proxy_set_header Host $host;
    }

    location /payment/ {
        proxy_pass http://10.0.1.206:5121;
        proxy_set_header Host $host;
    }

    location ~* \.pdf$ {
        add_header Content-Disposition "inline";
    }
}
