import os, re

def translate_html(source_path, dest_path, dictionary):
    with open(source_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Sort dictionary by length descending to prevent partial replacements
    sorted_dict = sorted(dictionary.items(), key=lambda x: len(x[0]), reverse=True)
    
    for ru, trans in sorted_dict:
        content = content.replace(ru, trans)
        
    with open(dest_path, 'w', encoding='utf-8') as f:
        f.write(content)

dict_en = {
    "Умный учёт активов компании": "Smart Company Asset Tracking",
    "Возможности": "Features",
    "Как работает": "How it works",
    "Тарифы": "Pricing",
    "Контакт": "Contact",
    "Начать бесплатно →": "Start for free →",
    "Начать бесплатно": "Start for free",
    "Новое поколение учёта активов": "Next generation asset tracking",
    "Учёт техники компании.<br>": "Company equipment tracking.<br>",
    "Умно. Быстро.": "Smart. Fast.",
    "Просто.": "Simple.",
    "ASSETO заменяет Excel-таблицы и бумажные акты. Всё оборудование компании,\n      документооборот и аналитика — в одном месте. Запуск за 15 минут.": "ASSETO replaces Excel spreadsheets and paper acts. All company equipment,\n      document flow, and analytics — in one place. Launch in 15 minutes.",
    "Попробовать бесплатно": "Try for free",
    "Смотреть демо": "Watch demo",
    "компаний на рынке": "companies on the market",
    "мин": "min",
    "до первого результата": "to first result",
    " ролей": " roles",
    "от сотрудника до CEO": "from employee to CEO",
    "Склад и Учёт": "Warehouse & Tracking",
    "АХО / IT · Управление оборудованием": "Ops / IT · Equipment Management",
    "Добавить": "Add",
    "Всего техники": "Total equipment",
    "У сотрудников": "With employees",
    "На ремонте": "Under repair",
    "Инв. №": "Inv. No.",
    "Категория": "Category",
    "Сотрудник": "Employee",
    "Статус": "Status",
    "Ноутбук": "Laptop",
    "Алишер И.": "Alisher I.",
    "Занято": "In use",
    "Монитор": "Monitor",
    "Дилноза К.": "Dilnoza K.",
    "Принтер": "Printer",
    "Свободно": "Free",
    "Бахром Т.": "Bakhrom T.",
    "Ремонт": "Repair",
    "Сканирование QR...": "Scanning QR...",
    "Ноутбук выдан": "Laptop issued",
    "Документ согласован": "Document approved",
    "Директор подписал акт": "Director signed the act",
    "Техника выдана": "Equipment issued",
    "ноутбук НТБ-089": "laptop NTB-089",
    "Алишер вернул технику": "Alisher returned equipment",
    "Подпись получена": "Signature received",
    "Доверяют в Узбекистане": "Trusted in Uzbekistan",
    "Проблема": "Problem",
    "Ваша компания теряет <span class=\"gradient-text\">деньги прямо сейчас</span>": "Your company is losing <span class=\"gradient-text\">money right now</span>",
    "Каждая компания сталкивается с одними и теми же проблемами": "Every company faces the same problems",
    "Excel-хаос": "Excel chaos",
    "Таблицы устарели, у каждого своя версия, формулы сломаны. Никто не знает что актуально.": "Spreadsheets are outdated, everyone has their own version, formulas are broken. Nobody knows what's up-to-date.",
    "💸 40+ часов/год на ручное обновление": "💸 40+ hours/year on manual updates",
    "Бумажные акты": "Paper acts",
    "Документы теряются, подписи подделываются, согласование занимает недели. Бухгалтерия в ужасе.": "Documents get lost, signatures are forged, approval takes weeks. Accounting is terrified.",
    "📋 3-5 дней на один акт передачи": "📋 3-5 days per transfer act",
    "Увольнение = хаос": "Offboarding = chaos",
    "Сотрудник уходит — вернул ли всю технику? Никто не знает. Тысячи долларов уходят вместе с ним.": "An employee leaves — did they return all equipment? Nobody knows. Thousands of dollars leave with them.",
    "🚪 3-5% активов теряется при оффбординге": "🚪 3-5% of assets lost during offboarding",
    "Инвентаризация = боль": "Inventory = pain",
    "Раз в год — неделя страданий. Ходят по кабинетам, сверяют бумажки. Всё равно находят ошибки.": "Once a year — a week of suffering. Walking through offices, checking papers. Errors are still found.",
    "📊 5-7 дней простоя команды ежегодно": "📊 5-7 days of team downtime annually",
    "Сравнение": "Comparison",
    "Хватит вести учёт <span class=\"gradient-text\">вслепую</span>": "Stop tracking <span class=\"gradient-text\">blindly</span>",
    "Посмотрите разницу между устаревшим подходом и современным решением.": "See the difference between the outdated approach and a modern solution.",
    "Хаос в Excel": "Chaos in Excel",
    "Наименование": "Name",
    "У кого": "Who has it",
    "Дата": "Date",
    "Неизвестно": "Unknown",
    "Сломан": "Broken",
    "Нет данных": "No data",
    "Порядок в ASSETO": "Order in ASSETO",
    "Система": "System",
    "Установлен в переговорной": "Installed in meeting room",
    "Ручной ввод данных": "Manual data entry",
    "Ошибки из-за человеческого фактора": "Errors due to human factor",
    "Сложно найти кто за что отвечает": "Hard to find who is responsible",
    "Нет истории перемещений": "No movement history",
    "Автоматическое сканирование QR": "Automatic QR scanning",
    "100% точность данных": "100% data accuracy",
    "Прозрачная ответственность (МОЛ)": "Transparent responsibility",
    "Полная история каждого устройства": "Full history of each device",
    "Всё в одном месте": "Everything in one place",
    "От закупки до списания — весь жизненный цикл оборудования под контролем.": "From purchase to write-off — the entire equipment lifecycle is under control.",
    "Выдача по QR-коду": "Issue via QR code",
    "Печатайте наклейки, сканируйте смартфоном. Оборудование выдается в 1 клик.": "Print labels, scan with a smartphone. Equipment is issued in 1 click.",
    "Электронные подписи": "Electronic signatures",
    "Сотрудники расписываются прямо на экране смартфона или планшета. Без бумаги.": "Employees sign directly on the screen of a smartphone or tablet. Paperless.",
    "Аналитика и бюджет": "Analytics & Budget",
    "Понимайте, сколько стоит ваше оборудование и когда его нужно менять.": "Understand how much your equipment costs and when to replace it.",
    "Инвентаризация": "Inventory",
    "Забудьте про недели сверок. Сканируйте кабинеты за минуты.": "Forget about weeks of reconciliations. Scan offices in minutes.",
    "API и Интеграции": "API & Integrations",
    "Свяжите ASSETO с вашей 1С, ERP или HR-системой.": "Connect ASSETO with your 1C, ERP, or HR system.",
    "Интеграции": "Integrations",
    "Работает с тем, что вы уже любите": "Works with what you already love",
    "Шаг 1": "Step 1",
    "Добавьте технику": "Add equipment",
    "Импортируйте из Excel или добавьте вручную. Система сгенерирует QR-коды для каждого устройства.": "Import from Excel or add manually. The system will generate QR codes for each device.",
    "Шаг 2": "Step 2",
    "Наклейте QR-коды": "Apply QR codes",
    "Распечатайте этикетки на обычном или термопринтере и наклейте на оборудование.": "Print labels on a regular or thermal printer and stick them on the equipment.",
    "Шаг 3": "Step 3",
    "Выдавайте в 1 клик": "Issue in 1 click",
    "Сканируйте код, выбирайте сотрудника. Акт формируется и подписывается электронно.": "Scan the code, select the employee. The act is generated and signed electronically.",
    "Роли": "Roles",
    "Для каждого в компании": "For everyone in the company",
    "ASSETO адаптируется под задачи каждого сотрудника, от рядового специалиста до руководителя.": "ASSETO adapts to the tasks of every employee, from a regular specialist to a manager.",
    "АХО / Склад": "Ops / Warehouse",
    "Учет, выдача и инвентаризация без нервов и бумаг.": "Tracking, issuing, and inventory without nerves and papers.",
    "IT отдел": "IT Department",
    "Контроль лицензий, ремонтов и апгрейдов техники.": "Control of licenses, repairs, and equipment upgrades.",
    "Бухгалтерия": "Accounting",
    "Всегда точные данные для баланса и амортизации.": "Always accurate data for balance and depreciation.",
    "Сотрудник": "Employee",
    "Прозрачный список того, что числится за тобой.": "Transparent list of what is assigned to you.",
    "Руководитель": "Manager",
    "Аналитика затрат и контроль сохранности активов.": "Cost analytics and asset preservation control.",
    "Служба безопасности": "Security",
    "Мониторинг перемещений и предотвращение краж.": "Movement monitoring and theft prevention.",
    "Частые вопросы": "FAQ",
    "Остались сомнения?": "Still have doubts?",
    "Мы готовы ответить на любые ваши вопросы": "We are ready to answer any of your questions",
    "Как долго внедрять ASSETO?": "How long does it take to implement ASSETO?",
    "В среднем запуск занимает 15-30 минут. Вы можете импортировать вашу текущую базу из Excel и сразу начать выдавать технику по-новому.": "On average, launch takes 15-30 minutes. You can import your current database from Excel and immediately start issuing equipment in a new way.",
    "Нужно ли покупать специальный сканер?": "Do I need to buy a special scanner?",
    "Нет. Вы можете использовать камеру любого смартфона (iOS/Android). Но если у вас есть профессиональный сканер штрих-кодов, он тоже будет работать.": "No. You can use the camera of any smartphone (iOS/Android). But if you have a professional barcode scanner, it will work too.",
    "Данные в безопасности?": "Is the data secure?",
    "Да. Сервера находятся в защищенном дата-центре в Узбекистане. Регулярные бэкапы и шифрование данных гарантируют сохранность. Для Enterprise-клиентов доступна установка на ваших серверах (on-premise).": "Yes. Servers are located in a secure data center in Uzbekistan. Regular backups and data encryption guarantee safety. For Enterprise clients, installation on your servers (on-premise) is available.",
    "Прозрачные тарифы": "Transparent pricing",
    "Никаких скрытых платежей. Выбирайте план под ваш размер.": "No hidden fees. Choose a plan for your size.",
    "Стартовый": "Starter",
    "Бесплатно": "Free",
    "Для маленьких команд": "For small teams",
    "До 10 пользователей": "Up to 10 users",
    "До 200 активов": "Up to 200 assets",
    "QR-коды": "QR codes",
    "Базовый документооборот": "Basic document flow",
    "Email поддержка": "Email support",
    "Расширенная аналитика": "Advanced analytics",
    "Telegram уведомления": "Telegram notifications",
    "Популярный": "Popular",
    "Бизнес": "Business",
    "Для растущих компаний": "For growing companies",
    "До 50 пользователей": "Up to 50 users",
    "До 2,000 активов": "Up to 2,000 assets",
    "QR-коды и сканер": "QR codes & scanner",
    "Полный документооборот": "Full document flow",
    "Аналитика и МОЛ": "Analytics & accountability",
    "Приоритетная поддержка": "Priority support",
    "Для крупных организаций": "For large organizations",
    "Без ограничений": "Unlimited",
    "Без ограничений активов": "Unlimited assets",
    "Личный менеджер": "Personal manager",
    "Self-hosted установка": "Self-hosted installation",
    "Интеграция с 1С, UzInfoCom": "Integration with 1C, UzInfoCom",
    "Кастомный дизайн": "Custom design",
    "Связаться с нами": "Contact us",
    "Государственные организации — специальные условия. Напишите нам.": "Government organizations — special conditions. Contact us.",
    "Начните прямо сейчас.<br>14 дней бесплатно.": "Start right now.<br>14 days free.",
    "Без кредитной карты. Без скрытых платежей. Отмена в любой момент.": "No credit card. No hidden fees. Cancel anytime.",
    "Попробовать ASSETO бесплатно": "Try ASSETO for free",
    "15 минут до запуска": "15 minutes to launch",
    "Поддержка на русском": "Support in Russian/English/Uzbek",
    "Данные в Узбекистане": "Data in Uzbekistan",
    "Свяжитесь с нами": "Contact us",
    "Ответим в течение часа в рабочее время. Если срочно — пишите в Telegram.": "We will answer within an hour during business hours. If urgent — write in Telegram.",
    "Ваше имя": "Your name",
    "Акмал Рашидов": "Akmal Rashidov",
    "Компания": "Company",
    "ООО Ромашка": "Romashka LLC",
    "Email или Telegram": "Email or Telegram",
    "Сколько сотрудников?": "How many employees?",
    "Получить демо-доступ →": "Get demo access →",
    "Ответим в Telegram или на email в течение часа": "We will answer in Telegram or by email within an hour",
    "Заявка отправлена!": "Request sent!",
    "Свяжемся с вами в течение часа": "We will contact you within an hour",
    "Умный учёт материальных<br>ценностей для бизнеса": "Smart tracking of material<br>assets for business",
    "Продукт": "Product",
    "О нас": "About us",
    "Блог": "Blog",
    "Поддержка": "Support",
    "Документация": "Documentation",
    "Узбекистан.": "Uzbekistan.",
    "Данные хранятся на серверах в Узбекистане": "Data is stored on servers in Uzbekistan"
}

dict_uz = {
    "Умный учёт активов компании": "Kompaniya aktivlarini aqlli hisobga olish",
    "Возможности": "Imkoniyatlar",
    "Как работает": "Qanday ishlaydi",
    "Тарифы": "Tariflar",
    "Контакт": "Aloqa",
    "Начать бесплатно →": "Bepul boshlash →",
    "Начать бесплатно": "Bepul boshlash",
    "Новое поколение учёта активов": "Aktivlarni hisobga olishning yangi avlodi",
    "Учёт техники компании.<br>": "Kompaniya texnikasi hisobi.<br>",
    "Умно. Быстро.": "Aqlli. Tez.",
    "Просто.": "Oddiy.",
    "ASSETO заменяет Excel-таблицы и бумажные акты. Всё оборудование компании,\n      документооборот и аналитика — в одном месте. Запуск за 15 минут.": "ASSETO Excel jadvallari va qog'oz dalolatnomalarini almashtiradi. Barcha kompaniya uskunalari,\n      hujjat aylanishi va tahliliy ma'lumotlar - bir joyda. 15 daqiqada ishga tushirish.",
    "Попробовать бесплатно": "Bepul sinab ko'rish",
    "Смотреть демо": "Demoni ko'rish",
    "компаний на рынке": "bozordagi kompaniyalar",
    "мин": "daq",
    "до первого результата": "birinchi natijagacha",
    " ролей": " rollar",
    "от сотрудника до CEO": "xodimdan to CEOgacha",
    "Склад и Учёт": "Ombor va Hisob",
    "АХО / IT · Управление оборудованием": "AXB / IT · Uskunalarni boshqarish",
    "Добавить": "Qo'shish",
    "Всего техники": "Jami texnika",
    "У сотрудников": "Xodimlarda",
    "На ремонте": "Ta'mirda",
    "Инв. №": "Inv. №",
    "Категория": "Kategoriya",
    "Сотрудник": "Xodim",
    "Статус": "Holat",
    "Ноутбук": "Noutbuk",
    "Алишер И.": "Alisher I.",
    "Занято": "Band",
    "Монитор": "Monitor",
    "Дилноза К.": "Dilnoza K.",
    "Принтер": "Printer",
    "Свободно": "Bo'sh",
    "Бахром Т.": "Bahrom T.",
    "Ремонт": "Ta'mir",
    "Сканирование QR...": "QR skanerlanmoqda...",
    "Ноутбук выдан": "Noutbuk berildi",
    "Документ согласован": "Hujjat kelishildi",
    "Директор подписал акт": "Direktor dalolatnomani imzoladi",
    "Техника выдана": "Texnika berildi",
    "ноутбук НТБ-089": "noutbuk NTB-089",
    "Алишер вернул технику": "Alisher texnikani qaytardi",
    "Подпись получена": "Imzo olindi",
    "Доверяют в Узбекистане": "O'zbekistonda ishonishadi",
    "Проблема": "Muammo",
    "Ваша компания теряет <span class=\"gradient-text\">деньги прямо сейчас</span>": "Kompaniyangiz <span class=\"gradient-text\">ayni paytda pul yo'qotmoqda</span>",
    "Каждая компания сталкивается с одними и теми же проблемами": "Har bir kompaniya bir xil muammolarga duch keladi",
    "Excel-хаос": "Excel-xaos",
    "Таблицы устарели, у каждого своя версия, формулы сломаны. Никто не знает что актуально.": "Jadvallar eskirgan, har kimda o'z versiyasi bor, formulalar buzilgan. Nima dolzarbligini hech kim bilmaydi.",
    "💸 40+ часов/год на ручное обновление": "💸 Yiliga 40+ soat qo'lda yangilashga ketadi",
    "Бумажные акты": "Qog'oz dalolatnomalar",
    "Документы теряются, подписи подделываются, согласование занимает недели. Бухгалтерия в ужасе.": "Hujjatlar yo'qoladi, imzolar soxtalashtiriladi, kelishuv haftalar davom etadi. Buxgalteriya dahshatda.",
    "📋 3-5 дней на один акт передачи": "📋 Bitta topshirish dalolatnomasi uchun 3-5 kun",
    "Увольнение = хаос": "Ishdan bo'shatish = xaos",
    "Сотрудник уходит — вернул ли всю технику? Никто не знает. Тысячи долларов уходят вместе с ним.": "Xodim ketyapti — u barcha texnikani qaytardimi? Hech kim bilmaydi. Minglab dollar u bilan birga ketadi.",
    "🚪 3-5% активов теряется при оффбординге": "🚪 Offbording paytida aktivlarning 3-5% yo'qoladi",
    "Инвентаризация = боль": "Inventarizatsiya = og'riq",
    "Раз в год — неделя страданий. Ходят по кабинетам, сверяют бумажки. Всё равно находят ошибки.": "Yilda bir marta — bir haftalik azob. Xonama-xona yurishadi, qog'ozlarni solishtirishadi. Baribir xatolar topiladi.",
    "📊 5-7 дней простоя команды ежегодно": "📊 Jamoaning har yili 5-7 kun bekor turishi",
    "Сравнение": "Taqqoslash",
    "Хватит вести учёт <span class=\"gradient-text\">вслепую</span>": "Hisobni <span class=\"gradient-text\">ko'r-ko'rona</span> yuritishni bas qiling",
    "Посмотрите разницу между устаревшим подходом и современным решением.": "Eskirgan yondashuv va zamonaviy yechim o'rtasidagi farqni ko'ring.",
    "Хаос в Excel": "Exceldagi xaos",
    "Наименование": "Nomi",
    "У кого": "Kimda",
    "Дата": "Sana",
    "Неизвестно": "Noma'lum",
    "Сломан": "Buzilgan",
    "Нет данных": "Ma'lumot yo'q",
    "Порядок в ASSETO": "ASSETO-dagi tartib",
    "Система": "Tizim",
    "Установлен в переговорной": "Muzokaralar xonasida o'rnatilgan",
    "Ручной ввод данных": "Ma'lumotlarni qo'lda kiritish",
    "Ошибки из-за человеческого фактора": "Inson omili tufayli xatolar",
    "Сложно найти кто за что отвечает": "Kim nima uchun javobgarligini topish qiyin",
    "Нет истории перемещений": "Ko'chishlar tarixi yo'q",
    "Автоматическое сканирование QR": "Avtomatik QR skanerlash",
    "100% точность данных": "Ma'lumotlarning 100% aniqligi",
    "Прозрачная ответственность (МОЛ)": "Shaffof javobgarlik (JSh)",
    "Полная история каждого устройства": "Har bir qurilmaning to'liq tarixi",
    "Всё в одном месте": "Barchasi bir joyda",
    "От закупки до списания — весь жизненный цикл оборудования под контролем.": "Xariddan hisobdan chiqarishgacha — uskunaning butun hayot aylanishi nazorat ostida.",
    "Выдача по QR-коду": "QR kod bo'yicha berish",
    "Печатайте наклейки, сканируйте смартфоном. Оборудование выдается в 1 клик.": "Stikerlarni chop eting, smartfon bilan skanerlang. Uskuna 1 marta bosish orqali beriladi.",
    "Электронные подписи": "Elektron imzolar",
    "Сотрудники расписываются прямо на экране смартфона или планшета. Без бумаги.": "Xodimlar to'g'ridan-to'g'ri smartfon yoki planshet ekranida imzo chekishadi. Qog'ozsiz.",
    "Аналитика и бюджет": "Tahlil va byudjet",
    "Понимайте, сколько стоит ваше оборудование и когда его нужно менять.": "Uskunangiz qancha turishini va qachon almashtirish kerakligini tushuning.",
    "Инвентаризация": "Inventarizatsiya",
    "Забудьте про недели сверок. Сканируйте кабинеты за минуты.": "Haftalab taqqoslashlarni unuting. Xonalarni daqiqalarda skanerlang.",
    "API и Интеграции": "API va Integratsiyalar",
    "Свяжите ASSETO с вашей 1С, ERP или HR-системой.": "ASSETO-ni o'zingizning 1C, ERP yoki HR tizimingiz bilan bog'lang.",
    "Интеграции": "Integratsiyalar",
    "Работает с тем, что вы уже любите": "Siz allaqachon yaxshi ko'rgan narsalar bilan ishlaydi",
    "Шаг 1": "1-qadam",
    "Добавьте технику": "Texnikani qo'shing",
    "Импортируйте из Excel или добавьте вручную. Система сгенерирует QR-коды для каждого устройства.": "Excel-dan import qiling yoki qo'lda qo'shing. Tizim har bir qurilma uchun QR-kodlarni yaratadi.",
    "Шаг 2": "2-qadam",
    "Наклейте QR-коды": "QR-kodlarni yopishtiring",
    "Распечатайте этикетки на обычном или термопринтере и наклейте на оборудование.": "Yorliqlarni oddiy yoki termal printerda chop eting va uskunaga yopishtiring.",
    "Шаг 3": "3-qadam",
    "Выдавайте в 1 клик": "1 marta bosishda bering",
    "Сканируйте код, выбирайте сотрудника. Акт формируется и подписывается электронно.": "Kodni skanerlang, xodimni tanlang. Dalolatnoma shakllantiriladi va elektron imzolanadi.",
    "Роли": "Rollar",
    "Для каждого в компании": "Kompaniyadagi har bir kishi uchun",
    "ASSETO адаптируется под задачи каждого сотрудника, от рядового специалиста до руководителя.": "ASSETO har bir xodimning vazifalariga moslashadi, oddiy mutaxassisdan tortib to rahbargacha.",
    "АХО / Склад": "AXB / Ombor",
    "Учет, выдача и инвентаризация без нервов и бумаг.": "Hisobga olish, tarqatish va inventarizatsiya - asablarsiz va qog'ozlarsiz.",
    "IT отдел": "IT bo'limi",
    "Контроль лицензий, ремонтов и апгрейдов техники.": "Litsenziyalar, ta'mirlash va texnika yangilanishlarini nazorat qilish.",
    "Бухгалтерия": "Buxgalteriya",
    "Всегда точные данные для баланса и амортизации.": "Balans va amortizatsiya uchun doimo aniq ma'lumotlar.",
    "Сотрудник": "Xodim",
    "Прозрачный список того, что числится за тобой.": "Sizga biriktirilgan narsalarning shaffof ro'yxati.",
    "Руководитель": "Rahbar",
    "Аналитика затрат и контроль сохранности активов.": "Xarajatlar tahlili va aktivlar xavfsizligini nazorat qilish.",
    "Служба безопасности": "Xavfsizlik xizmati",
    "Мониторинг перемещений и предотвращение краж.": "Harakatlarni kuzatish va o'g'irlikning oldini olish.",
    "Частые вопросы": "Ko'p so'raladigan savollar",
    "Остались сомнения?": "Shubhalaringiz qoldimi?",
    "Мы готовы ответить на любые ваши вопросы": "Biz har qanday savolingizga javob berishga tayyormiz",
    "Как долго внедрять ASSETO?": "ASSETO-ni joriy etish qancha vaqt oladi?",
    "В среднем запуск занимает 15-30 минут. Вы можете импортировать вашу текущую базу из Excel и сразу начать выдавать технику по-новому.": "O'rtacha, ishga tushirish 15-30 daqiqa davom etadi. Joriy bazangizni Excel-dan import qilishingiz va darhol texnikani yangi usulda berishni boshlashingiz mumkin.",
    "Нужно ли покупать специальный сканер?": "Maxsus skaner sotib olish kerakmi?",
    "Нет. Вы можете использовать камеру любого смартфона (iOS/Android). Но если у вас есть профессиональный сканер штрих-кодов, он тоже будет работать.": "Yo'q. Siz har qanday smartfon kamerasidan (iOS/Android) foydalanishingiz mumkin. Ammo agar sizda professional shtrix-kod skaneri bo'lsa, u ham ishlaydi.",
    "Данные в безопасности?": "Ma'lumotlar xavfsizmi?",
    "Да. Сервера находятся в защищенном дата-центре в Узбекистане. Регулярные бэкапы и шифрование данных гарантируют сохранность. Для Enterprise-клиентов доступна установка на ваших серверах (on-premise).": "Ha. Serverlar O'zbekistondagi xavfsiz ma'lumotlar markazida joylashgan. Muntazam zaxira nusxalari va ma'lumotlarni shifrlash xavfsizlikni kafolatlaydi. Enterprise mijozlari uchun o'z serverlaringizga o'rnatish (on-premise) mavjud.",
    "Прозрачные тарифы": "Shaffof tariflar",
    "Никаких скрытых платежей. Выбирайте план под ваш размер.": "Yashirin to'lovlar yo'q. O'lchamingizga mos rejani tanlang.",
    "Стартовый": "Boshlang'ich",
    "Бесплатно": "Bepul",
    "Для маленьких команд": "Kichik jamoalar uchun",
    "До 10 пользователей": "10 tagacha foydalanuvchi",
    "До 200 активов": "200 tagacha aktiv",
    "QR-коды": "QR-kodlar",
    "Базовый документооборот": "Asosiy hujjat aylanishi",
    "Email поддержка": "Email orqali yordam",
    "Расширенная аналитика": "Kengaytirilgan tahlil",
    "Telegram уведомления": "Telegram bildirishnomalari",
    "Популярный": "Ommabop",
    "Бизнес": "Biznes",
    "Для растущих компаний": "O'sayotgan kompaniyalar uchun",
    "До 50 пользователей": "50 tagacha foydalanuvchi",
    "До 2,000 активов": "2000 tagacha aktiv",
    "QR-коды и сканер": "QR-kodlar va skaner",
    "Полный документооборот": "To'liq hujjat aylanishi",
    "Аналитика и МОЛ": "Tahlil va JSh",
    "Приоритетная поддержка": "Ustuvor qo'llab-quvvatlash",
    "Для крупных организаций": "Yirik tashkilotlar uchun",
    "Без ограничений": "Cheklovlarsiz",
    "Без ограничений активов": "Aktivlar bo'yicha cheklovlarsiz",
    "Личный менеджер": "Shaxsiy menejer",
    "Self-hosted установка": "Self-hosted o'rnatish",
    "Интеграция с 1С, UzInfoCom": "1C, UzInfoCom bilan integratsiya",
    "Кастомный дизайн": "Shaxsiy dizayn",
    "Связаться с нами": "Biz bilan bog'laning",
    "Государственные организации — специальные условия. Напишите нам.": "Davlat tashkilotlari — maxsus shartlar. Bizga yozing.",
    "Начните прямо сейчас.<br>14 дней бесплатно.": "Hozir boshlang.<br>14 kun bepul.",
    "Без кредитной карты. Без скрытых платежей. Отмена в любой момент.": "Kredit kartasiz. Yashirin to'lovlarsiz. Istalgan vaqtda bekor qilish.",
    "Попробовать ASSETO бесплатно": "ASSETO-ni bepul sinab ko'ring",
    "15 минут до запуска": "Ishga tushirishgacha 15 daqiqa",
    "Поддержка на русском": "Rus/Ingliz/O'zbek tillarida yordam",
    "Данные в Узбекистане": "Ma'lumotlar O'zbekistonda",
    "Свяжитесь с нами": "Biz bilan bog'lanish",
    "Ответим в течение часа в рабочее время. Если срочно — пишите в Telegram.": "Ish vaqtida bir soat ichida javob beramiz. Agar shoshilinch bo'lsa — Telegram-ga yozing.",
    "Ваше имя": "Ismingiz",
    "Акмал Рашидов": "Akmal Rashidov",
    "Компания": "Kompaniya",
    "ООО Ромашка": "Romashka MChJ",
    "Email или Telegram": "Email yoki Telegram",
    "Сколько сотрудников?": "Qancha xodim?",
    "Получить демо-доступ →": "Demo ruxsat olish →",
    "Ответим в Telegram или на email в течение часа": "Bir soat ichida Telegram yoki elektron pochta orqali javob beramiz",
    "Заявка отправлена!": "Arizangiz yuborildi!",
    "Свяжемся с вами в течение часа": "Bir soat ichida siz bilan bog'lanamiz",
    "Умный учёт материальных<br>ценностей для бизнеса": "Biznes uchun moddiy boyliklarni<br>aqlli hisobga olish",
    "Продукт": "Mahsulot",
    "О нас": "Biz haqimizda",
    "Блог": "Blog",
    "Поддержка": "Yordam",
    "Документация": "Hujjatlar",
    "Узбекистан.": "O'zbekiston.",
    "Данные хранятся на серверах в Узбекистане": "Ma'lumotlar O'zbekistondagi serverlarda saqlanadi"
}

translate_html('landing/index.html', 'landing/index_en.html', dict_en)
translate_html('landing/index.html', 'landing/index_uz.html', dict_uz)

# Update index.html, index_en.html, index_uz.html to have a language switcher
def add_switcher(filepath, current_lang):
    with open(filepath, 'r', encoding='utf-8') as f:
        html = f.read()
    
    # Simple CSS to style the switcher gracefully
    switcher = f"""
    <div class="lang-switcher" style="display:flex; gap:12px; margin-left:24px; font-size:13px; font-weight:800;">
      <a href="index.html" style="color: {'var(--accent)' if current_lang == 'ru' else 'var(--text2)'}; text-decoration:none; transition:0.2s;">RU</a>
      <a href="index_en.html" style="color: {'var(--accent)' if current_lang == 'en' else 'var(--text2)'}; text-decoration:none; transition:0.2s;">EN</a>
      <a href="index_uz.html" style="color: {'var(--accent)' if current_lang == 'uz' else 'var(--text2)'}; text-decoration:none; transition:0.2s;">UZ</a>
    </div>
    """
    
    # Avoid double insertion
    if 'class="lang-switcher"' not in html:
        html = html.replace('<div class="nav-cta">', switcher + '\n    <div class="nav-cta">')
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(html)

add_switcher('landing/index.html', 'ru')
add_switcher('landing/index_en.html', 'en')
add_switcher('landing/index_uz.html', 'uz')

print("Translation files generated successfully.")
